language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  
env:
  - MONGO_VERSION=1.2.12

before_script:
  - phpenv config-add travis.php.ini
  - wget http://pecl.php.net/get/mongo-1.2.10.tgz
  - tar -xzf mongo-1.2.10.tgz
  - sh -c "cd mongo-1.2.10 && phpize && ./configure && sudo make install"
  - echo "extension=mongo.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s|.*:\s*||"`
  - composer install --dev --prefer-source

script: phpunit --coverage-text

notifications:
  email:
    - valentin.ferriere@gmail.com